"""assignments table

Revision ID: 543c06094cb8
Revises: 670f396813ac
Create Date: 2024-01-23 19:14:24.404499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543c06094cb8'
down_revision = '670f396813ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=30), nullable=True))

    # ### end Alembic commands ###
