"""assignments table

Revision ID: 670f396813ac
Revises: 6915a2a13155
Create Date: 2024-01-18 22:19:56.261618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670f396813ac'
down_revision = '6915a2a13155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
