"""assignments table

Revision ID: 7fa63a9c738c
Revises: 543c06094cb8
Create Date: 2024-01-23 19:48:01.008341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa63a9c738c'
down_revision = '543c06094cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_assignments_subject')
        batch_op.create_index(batch_op.f('ix_assignments_subject'), ['subject'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_subject'))
        batch_op.create_index('ix_assignments_subject', ['subject'], unique=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
